### ISSUE TITLE
Does not respect basicprofile path given in properties file

### ISSUE THREAD

**Issue by WebDevBren** [SIMPATICOProject/logs#7]
In our simpatico.properties file we had the following config
```
~snip~
authentication.use=true
authentication.url=https://auth.sparta.simpatico-project.eu
authentication.path=/aac/resources/access
authentication.basicprofile.path=/aac/basicprofile/me
~snip~
```
however when the LOG was attempting to authenticate with the aac it ignores the authentication.basicprofile.path and attempts to go straight to `https://auth.sparta.simpatico-project.eu/basicprofile/me` which of course, gives a 404 error. 

This is resolvable by changing the authentication.url to include the /aac (https://auth.sparta.simpatico-project.eu/aac)

but of course this sounds to me like something the path should change.

**Comment by jrgaston-hib** [comment]
That error was solved two commits ago.
Update your project to get the last changes and KPIs functionallity.

I close this issue. If there is another problem please reopen it.
