### ISSUE TITLE
Crashes whenever receives invalid response in the logs.

### ISSUE THREAD

**Issue by Ulisses85** [SIMPATICOProject/logs#8]
Hello guys,

component crashes whenever receives invalid response in the logs:

exception

javax.servlet.ServletException: Filter execution threw an exception
	com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:174)
	com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:237)
root cause

java.lang.UnsupportedClassVersionError: org/elasticsearch/index/engine/DocumentMissingException : Unsupported major.minor version 52.0 (unable to load class org.elasticsearch.index.engine.DocumentMissingException)
	org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:3226)
	org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:1409)
	org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1897)
	org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1771)
	es.hiiberia.simpatico.filters.AuthenticationFilter.doFilter(AuthenticationFilter.java:72)
	com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:174)
	com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:237)

**Comment by breningham** [comment]
To extend upon this issue. 

The eSM Will fail to connect to the Log server due to authentication issues. Further the configuration of the tool is useless as even if we use a custom url for the ctz it will expect the ctz to be configured in a non-standard way, and no easy way to reconfigure this. 

There seems to be almost no error handling going on, and code quality is poor.

**Comment by breningham** [comment]
this was resolved by updating the runner (in the dockerfile) to use tomcat with jre8 (since its built with jdk8)

**Comment by smendez-hi** [comment]
I'm closing this one because it looks to be resolved.
